### ISSUE TITLE
Tag 4 not found in repository docker.io/keymetrics/pm2-docker-alpine

### ISSUE THREAD

**Issue by AleksMeshkov** [keymetrics/pm2-docker-alpine#10]
`$ docker pull keymetrics/pm2-docker-alpine:4`
`Pulling repository docker.io/keymetrics/pm2-docker-alpine Tag 4 not found in repository docker.io/keymetrics/pm2-docker-alpine`

**Comment by Xoib** [comment]
Use the tag latest instead of 4
```docker pull keymetrics/pm2-docker-alpine:latest```

**Comment by AleksMeshkov** [comment]
@Xoib as far as I know the ```:latest``` tag has nodejs v6 onboard. But I need LTS 4th version.

**Comment by Xoib** [comment]
@AleksMeshkov so you should use this repository : https://github.com/ruhmesmeile/pm2-docker-alpine instead of this one because currently we only have the v6 linked.

**Comment by gerard-mailtrack** [comment]
At this moment, the two available tags are:

- `:latest`: Which has node v7.3.0 
- `:v6`: Which has node v4.4.7 (last updated 6 months ago)

There don't seem to be any stable, up-to-date images here.

**Comment by simonepri** [comment]
@gerard-mailtrack 
Check this
https://github.com/keymetrics/pm2-docker-alpine/pull/11#issuecomment-275711273

**Comment by simonepri** [comment]
The list of the new tags is available here:
https://hub.docker.com/r/keymetrics/pm2-docker-alpine/tags/
