### ISSUE TITLE
Update PM2 Documentation

### ISSUE THREAD

**Issue by simonepri** [keymetrics/pm2-docker-alpine#13]
These information should be changed accoringly to the new tags available.
http://pm2.keymetrics.io/docs/usage/docker-pm2-nodejs/#official-docker-image

**Comment by Unitech** [comment]
Quite straightforward to edit the pm2 doc: https://github.com/pm2-hive/pm2-hive.github.io/blob/master/docs/features/docker.md

btw I'm currently having small issue with pm2-docker-alpine and docker-compose http://stackoverflow.com/questions/41910272/current-folder-does-not-get-exposed-to-docker

**Comment by simonepri** [comment]
Thank you, I didn't know that the documentation was open source.

Regarding the issue with pm2-docker-alpine
Currently I'm using it in production and it works quite well. (I don't use docker-compose)

**Comment by Unitech** [comment]
Finally I fixed it by removing all containers and reinstalling the whole kitchen sink - pm2-docker-alpine works pretty well, but it would be great to be able to change the configuration file (not only process.yml) - maybe with an environment variable? I'm creating an issue

Yes there is a button on each page to edit the right file in the github repo, it should be more visible

**Comment by simonepri** [comment]
https://github.com/pm2-hive/pm2-hive.github.io/pull/53
