### ISSUE TITLE
Allow to change the configuration filename in the Dockerfile

### ISSUE THREAD

**Issue by Unitech** [keymetrics/pm2-docker-alpine#14]
That would be nice to be able to change the start [file](https://github.com/keymetrics/pm2-docker-alpine/blob/master/Dockerfile#L14)

- Environment variable?

**Comment by simonepri** [comment]
How that could be useful?
I mean I can just edit the CMD in your own dockerfile
For istance in my dockerfile I have:
```
FROM keymetrics/pm2-docker-alpine:latest
[...]
CMD [ "pm2-docker", "start", "pm2.json" ]
```

**Comment by Unitech** [comment]
When using docker-compose, I might have just one single file (docker-compose.yml)

In this case it would be helpful to easily configure the Dockerfile via environment to change the configuration file for example

**Comment by simonepri** [comment]
You can specify it using command:
https://docs.docker.com/compose/compose-file/#/command

**Comment by Unitech** [comment]
great, I was just throwing ideas :) 
I've added a container under the tag next with pm2@next
