### ISSUE TITLE
Can't find Python executable "python"

### ISSUE THREAD

**Issue by CowPanda** [keymetrics/pm2-docker-alpine#15]
> env: mac osx

Some package will be dependent on `python` when `gyp rebulid` , for example `canvas` it will throw `python not found` but official docker images does not include such as `python/g++ ... ...` . it must be manually add  or build in `Dockerfile`?
```
> canvas@1.6.4 install /app/node_modules/canvas
> node-gyp rebuild

gyp info it worked if it ends with ok
gyp info using node-gyp@3.4.0
gyp info using node@6.9.4 | linux | x64
gyp ERR! configure error 
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.

```

**Comment by CowPanda** [comment]
My current alternative solution as follows:

```
docker run --rm -v "${PWD}":/app -w /app node:latest npm install  
```

**Comment by simonepri** [comment]
The building tools are not included in the image for space reasons.
If you need it while installing your dependencies, you need to install them manually in your `Dockerfile` and at the end of you `Dockerfile` uninstall them again.
Never leave them installed if your code does not use it after the building process.

**Comment by simonepri** [comment]
@CowPanda I close the issue, feel free to comment again if you need it.

**Comment by infinitytmbots** [comment]
Occuring for me. Debian - Using `FROM keymetrics/pm2:latest-alpine`
