### ISSUE TITLE
Change repo description.

### ISSUE THREAD

**Issue by simonepri** [keymetrics/pm2-docker-alpine#24]
Emoji are cool 😎
What if we change the description of the repo
From:

> Node.js lightweight Docker image including the PM2 runtime

To:

> 🐳 Official Docker Image for PM2 runtime

**Comment by Unitech** [comment]
Hey @simonepri, totally agree, that is more sexy. I gave you the admin rights on this repo, feel free to update the description!

**Comment by simonepri** [comment]
Thanks 🎉
