### ISSUE TITLE
Branch releases on hub.docker.com

### ISSUE THREAD

**Issue by julrich** [keymetrics/pm2-docker-alpine#8]
Not sure if those were present before the move, but right now the mentioned branches (0.12, 4) don't exist as Tags / Builds on hub.docker.com.

Can you quickly re-add those? Otherwise we would have to fork to get a running 0.12 build. And on a more general note: Is docker-volume meant as a 1:1 replacement for pm2-docker-alpine? Wasn't able to find any documentation / info on the move, but maybe I'm just not looking at the right places? I'm just asking, because I saw no further mention in this repository about passing the pm2-config file as an environment variable. Pretty sure that was possible before.

Would hate to be building upon this, when I can't be sure that it will provide some form of stability in the future. Suppose we built upon pm2-docker-alpine, and our infrastructure expected for those environment variables to work, we would, potentially, be in a lot of trouble right now. Would love to mitigate that risk by knowing the plan / future for this repository / organisation.

**Comment by Unitech** [comment]
Yes sorry about that, this docker image has not been officially release, that's why we are thinking about some naming stuff and so on.

**Finally we moved it back to keymetrics/pm2-docker-alpine, and it will stay like that now.**

All branches has been rebuilt,

**Comment by julrich** [comment]
Thanks for the quick feedback, very much appreciated! :)

The combination of a changed repo-name, mostly the same documentation and the missing hub.docker.com releases was really confusing!

**Comment by julrich** [comment]
Though I'm still not seeing the releases on https://hub.docker.com/r/keymetrics/pm2-docker-alpine/tags/.

Not sure if you're just missing some rules to build the branches, of if you had set explicit tags before. It's still not possible to docker pull 0.12 or 4.
